[[label]]
name = "bug"
description = "Something isn't working as expected. / Coś nie działa zgodnie z oczekiwaniami."
color = "d73a4a"

[[label]]
name = "enhancement"
description = "Improvement to existing feature. / Ulepszenie istniejącej funkcji."
color = "a2eeef"

[[label]]
name = "feature"
description = "New major functionality. / Nowa funkcjonalność."
color = "0e8a16"

[[label]]
name = "refactor"
description = "Code-only changes without functional impact. / Zmiany strukturalne w kodzie."
color = "f4b942"

[[label]]
name = "documentation"
description = "Documentation improvements or additions. / Zmiany w dokumentacji."
color = "0075ca"

[[label]]
name = "question"
description = "Further information is requested. / Prośba o dodatkowe informacje."
color = "d876e3"

[[label]]
name = "design"
description = "UI/UX or visual improvements. / Zmiany wizualne, UX/UI."
color = "ff69b4"

[[label]]
name = "good first issue"
description = "Ideal for newcomers. / Dobre na pierwszy wkład."
color = "7057ff"

[[label]]
name = "help wanted"
description = "Extra attention is needed. / Potrzebna pomoc."
color = "008672"

[[label]]
name = "needs review"
description = "Needs code or decision review. / Wymaga przeglądu."
color = "fbca04"

[[label]]
name = "needs reproduction"
description = "Bug needs to be reproduced. / Wymaga odtworzenia błędu."
color = "ffcc00"

[[label]]
name = "in progress"
description = "Work on this is actively ongoing. / Praca w toku."
color = "1d76db"

[[label]]
name = "on hold"
description = "Work is paused for now. / Praca wstrzymana."
color = "e99695"

[[label]]
name = "blocked"
description = "Blocked by another issue or dependency. / Zablokowane przez zależność."
color = "f9d0c4"

[[label]]
name = "duplicate"
description = "This issue or PR already exists. / Duplikat istniejącego zgłoszenia."
color = "cfd3d7"

[[label]]
name = "invalid"
description = "Not a valid issue or doesn't apply. / Niepoprawne zgłoszenie."
color = "e4e669"

[[label]]
name = "wontfix"
description = "This will not be addressed. / Nie będzie realizowane."
color = "ffffff"

[[label]]
name = "priority: high"
description = "Must be addressed as soon as possible. / Wysoki priorytet."
color = "b60205"

[[label]]
name = "priority: medium"
description = "Important but not urgent. / Umiarkowany priorytet."
color = "fbca04"

[[label]]
name = "priority: low"
description = "Can be addressed later. / Niski priorytet."
color = "0e8a16"

[[label]]
name = "frontend"
description = "UI or web-related work. / Interfejs użytkownika, front-end."
color = "5319e7"

[[label]]
name = "backend"
description = "Backend or logic-related work. / Logika systemu, backend."
color = "e99695"

[[label]]
name = "cli"
description = "Command-line interface components. / Interfejs wiersza poleceń."
color = "8b4513"

[[label]]
name = "sim-core"
description = "Simulation engine or core logic. / Silnik symulacyjny lub rdzeń."
color = "00b0f0"

[[label]]
name = "data"
description = "Data processing, I/O, formats. / Przetwarzanie danych i formaty."
color = "9a6324"
